apiVersion: v1
kind: Service
metadata:
  name: animea-friends-svc
  labels:
    app: animea-friends
spec:
  selector:
    app: animea-friends
  ports:
  - name: http-svc-port
    port: 8080
    targetPort: http-port
    nodePort: 30080
  type: NodePort
